fn main() {
    // Pin cargo's incremental-build inputs to every icon path the
    // build can consume, plus the Tauri config itself, so a fresh
    // `npm run icons` (or any single-file icon edit) actually
    // invalidates the cached .exe. cargo's `rerun-if-changed` is
    // exact-string matched; we list paths defensively even where we
    // believe tauri-build also tracks them — duplicating an entry is
    // free, but missing one silently reverts the original
    // stale-icon-after-regen bug.
    //
    // Categories:
    //   1. tauri.conf.json: drives the bundle config.
    //   2. The five paths in `bundle.icon`: the icons
    //      `tauri::generate_context!()` actually embeds at compile
    //      time. tauri-build *probably* tracks these too, but cargo-
    //      side cache invalidation is too important to trust to
    //      that.
    //   3. Square*Logo / StoreLogo / icon.png / 64x64.png: belt-and-
    //      braces paths NOT referenced by tauri.conf.json — they
    //      were left on disk by a previous `npx tauri icon` run and
    //      are now regenerated by scripts/gen-favicon.mjs. cargo
    //      would otherwise have no reason to rebuild when only these
    //      files change, so listing them here closes that last gap.
    println!("cargo:rerun-if-changed=tauri.conf.json");
    println!("cargo:rerun-if-changed=icons/32x32.png");
    println!("cargo:rerun-if-changed=icons/128x128.png");
    println!("cargo:rerun-if-changed=icons/128x128@2x.png");
    println!("cargo:rerun-if-changed=icons/icon.ico");
    println!("cargo:rerun-if-changed=icons/icon.icns");
    println!("cargo:rerun-if-changed=icons/64x64.png");
    println!("cargo:rerun-if-changed=icons/icon.png");
    println!("cargo:rerun-if-changed=icons/Square30x30Logo.png");
    println!("cargo:rerun-if-changed=icons/Square44x44Logo.png");
    println!("cargo:rerun-if-changed=icons/Square71x71Logo.png");
    println!("cargo:rerun-if-changed=icons/Square89x89Logo.png");
    println!("cargo:rerun-if-changed=icons/Square107x107Logo.png");
    println!("cargo:rerun-if-changed=icons/Square142x142Logo.png");
    println!("cargo:rerun-if-changed=icons/Square150x150Logo.png");
    println!("cargo:rerun-if-changed=icons/Square284x284Logo.png");
    println!("cargo:rerun-if-changed=icons/Square310x310Logo.png");
    println!("cargo:rerun-if-changed=icons/StoreLogo.png");
    tauri_build::build()
}
